include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/features/**/*.dart" # Optional: common if tests have generated bits
  errors:
    deprecated_member_use: ignore

linter:
  rules:
    # Add your custom rules here
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    use_build_context_synchronously: true
