include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Add your custom rules here
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    use_build_context_synchronously: true
